FROM mambaorg/micromamba:latest

RUN micromamba install -y -n base -c conda-forge \
    poetry \
    go-waitforit \
    curl

ARG MAMBA_DOCKERFILE_ACTIVATE=1

WORKDIR /src

COPY --chown=$MAMBA_USER:$MAMBA_USER pyproject.toml .

RUN poetry install --no-root

COPY --chown=$MAMBA_USER:$MAMBA_USER . .

RUN poetry install

CMD waitforit -address http://oidc_server_mock -- poetry run pytest -s tests/
